# .github/workflows/main.yml
    
    name: Meterian Scanner workflow

on:
  pull_request:
    types:
      - closed

jobs:
  meterian_scan:
    name: Meterian client scan
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Meterian Scanner
        uses: MeterianHQ/meterian-github-action@v1.0.13
        with:
          oss: true
